### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (0...

### ISSUE THREAD

**Issue by jlvivero** [v3ss0n/steam-pirate-ui#3]
[Enter steps to reproduce below:]
Try to change settings on the pirate ui
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [steam-pirate-ui](https://github.com/v3ss0n/steam-pirate-ui) package, v0.6.1
### Stack Trace

Uncaught IndexSizeError: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (0) is larger than the maximum index (4294967295).

```
At /home/jl/.atom/packages/steam-pirate-ui/lib/config.coffee:31

Error: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (0) is larger than the maximum index (4294967295).
  at Error (native)
  at setBlurRadius (/home/jl/.atom/packages/steam-pirate-ui/lib/config.coffee:31:21)
  at /home/jl/.atom/packages/steam-pirate-ui/lib/config.coffee:52:7
  at /usr/share/atom/resources/app.asar/src/config.js:587:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:772:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:564:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:192:28)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:238:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1273:25

```
### Commands

```
  3x -3:57.7.0 core:backspace (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:57.2.0 editor:consolidate-selections (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:57.2.0 core:cancel (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:56 editor:consolidate-selections (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:56 core:cancel (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:55.4.0 editor:consolidate-selections (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:55.4.0 core:cancel (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:54.9.0 editor:consolidate-selections (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:54.9.0 core:cancel (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:53.3.0 core:confirm (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:43.9.0 editor:consolidate-selections (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:43.9.0 core:cancel (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
  3x -3:42.8.0 core:backspace (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:42.4.0 editor:consolidate-selections (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
     -3:42.4.0 core:cancel (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
  5x -0:06.8.0 core:confirm (atom-text-editor#steam-pirate-ui.backgroundImage.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "steam-pirate-ui",
      "steam-pirate-syntax"
    ],
    "autoHideMenuBar": true
  },
  "steam-pirate-ui": {
    "blurBackground": "1"
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
fuzzy-theme-switcher, v1.0.0
steam-pirate-syntax, v0.3.0
steam-pirate-ui, v0.6.1

# Dev
No dev packages
```

**Comment by v3ss0n** [comment]
I will take a look

**Comment by v3ss0n** [comment]
I can't reproduce

**Comment by alphacentory** [comment]
I have the same issue on mac os Sierra. I just switched back to Atom from intellij. Fresh install. 
1. installed steampunk. 
2. installed hack the kernal ui 
3. switched to hack the kernal 
4. switched back. 
5. steam punk ui background image gone and get it back. and getting UncaughtIndezSize error. 

*Sorry for grammar / spelling on my phone.
